import json
import ollama
import os
from datetime import datetime

def load_json(file_path):
    """Load JSON data from a file."""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        raise ValueError(f"Error loading JSON file: {e}")

def analyze_whale_purchases(data):
    """
    Analyze purchases made by whales using the Ollama LLM.
    
    Args:
        data (dict): Financial data loaded from the JSON file.
    
    Returns:
        str: Insights generated by the model.
    """
    try:
        # Convert the entire financial data to a string for analysis
        financial_data_str = json.dumps(data, indent=4)
        
        # Define the system prompt for analyzing whale purchases
        system_prompt = (
            "You are a financial analyst specializing in identifying patterns "
            "and insights into purchases made by high-value customers (whales). "
            "Your task is to analyze the provided financial data and provide "
            "actionable insights into whale behavior."
        )
        
        # Make the Ollama API call
        response = ollama.chat(
            model="llama3.2:latest",  # Replace with your actual model name
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Analyze the following financial data for insights into whale purchases, particularly our focus is how much whales cost to engage, to onboard and the split by country or any patterns:\n{financial_data_str}"}
            ]
        )
        
        # Extract and return the model's response
        return response['message']['content']
    
    except Exception as e:
        raise ValueError(f"Error during analysis of whale purchases: {e}")

def save_insights_to_file(insights):
    """
    Save the insights to a text file with a timestamp in the output folder.
    
    Args:
        insights (str): The insights generated by the model.
    """
    try:
        # Create the output folder if it doesn't exist
        output_folder = "output"
        os.makedirs(output_folder, exist_ok=True)
        
        # Generate a timestamped filename
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        file_name = f"whale_insights_{timestamp}.txt"
        file_path = os.path.join(output_folder, file_name)
        
        # Write the insights to the file
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(insights)
        
        print(f"Insights saved to: {file_path}")
    
    except Exception as e:
        raise ValueError(f"Error saving insights to file: {e}")

def main():
    # Path to your JSON file
    json_file_path = "test.json"
    
    # Load the financial data from the JSON file
    financial_data = load_json(json_file_path)
    
    # Analyze the data for whale purchase insights
    insights = analyze_whale_purchases(financial_data)
    
    # Print the insights
    print("Insights into Whale Purchases:")
    print(insights)
    
    # Save the insights to a file
    save_insights_to_file(insights)

if __name__ == "__main__":
    main()